-- V034__seed_built_in_templates.sql — the five shipped institution templates (TMPL-02)
--
-- Guarded inserts rather than plain ones: seeding must be idempotent so a schema reset, or a
-- repeated run against an existing database, cannot duplicate the built-ins.

INSERT INTO institution_templates (tenant_id, name, description, institution_type, configuration_json, is_built_in)
SELECT NULL, 'Primary School', 'Six shorter periods with an early lunch, suited to a single class teacher.', 'PRIMARY', '{"bellSchedule": {"name": "Primary School Bell Schedule", "periods": [{"name": "Period 1", "startTime": "08:00", "endTime": "08:45", "isBreak": false, "isLunch": false, "ordinal": 1}, {"name": "Period 2", "startTime": "08:45", "endTime": "09:30", "isBreak": false, "isLunch": false, "ordinal": 2}, {"name": "Lunch", "startTime": "09:30", "endTime": "10:15", "isBreak": false, "isLunch": true, "ordinal": 3}, {"name": "Period 4", "startTime": "10:15", "endTime": "11:00", "isBreak": false, "isLunch": false, "ordinal": 4}, {"name": "Period 5", "startTime": "11:00", "endTime": "11:45", "isBreak": false, "isLunch": false, "ordinal": 5}, {"name": "Period 6", "startTime": "11:45", "endTime": "12:30", "isBreak": false, "isLunch": false, "ordinal": 6}]}, "settings": {"locale": "en-GB", "timezone": "Europe/London", "schedulingCycle": {"daysInCycle": 5}}, "terminology": {"class": "Class", "period": "Period", "teacher": "Teacher", "subject": "Subject"}, "constraintDefaults": {"lessonLength": 45, "maxConsecutivePeriods": 3}}', TRUE
WHERE NOT EXISTS (SELECT 1 FROM institution_templates WHERE is_built_in = TRUE AND name = 'Primary School');

INSERT INTO institution_templates (tenant_id, name, description, institution_type, configuration_json, is_built_in)
SELECT NULL, 'Secondary School', 'Eight periods across a five-day week — the most common secondary pattern.', 'SECONDARY', '{"bellSchedule": {"name": "Secondary School Bell Schedule", "periods": [{"name": "Period 1", "startTime": "08:00", "endTime": "08:45", "isBreak": false, "isLunch": false, "ordinal": 1}, {"name": "Period 2", "startTime": "08:45", "endTime": "09:30", "isBreak": false, "isLunch": false, "ordinal": 2}, {"name": "Period 3", "startTime": "09:30", "endTime": "10:15", "isBreak": false, "isLunch": false, "ordinal": 3}, {"name": "Period 4", "startTime": "10:15", "endTime": "11:00", "isBreak": false, "isLunch": false, "ordinal": 4}, {"name": "Lunch", "startTime": "11:00", "endTime": "11:45", "isBreak": false, "isLunch": true, "ordinal": 5}, {"name": "Period 6", "startTime": "11:45", "endTime": "12:30", "isBreak": false, "isLunch": false, "ordinal": 6}, {"name": "Period 7", "startTime": "12:30", "endTime": "13:15", "isBreak": false, "isLunch": false, "ordinal": 7}, {"name": "Period 8", "startTime": "13:15", "endTime": "14:00", "isBreak": false, "isLunch": false, "ordinal": 8}]}, "settings": {"locale": "en-GB", "timezone": "Europe/London", "schedulingCycle": {"daysInCycle": 5}}, "terminology": {"class": "Class", "period": "Period", "teacher": "Teacher", "subject": "Subject"}, "constraintDefaults": {"lessonLength": 45, "maxConsecutivePeriods": 4}}', TRUE
WHERE NOT EXISTS (SELECT 1 FROM institution_templates WHERE is_built_in = TRUE AND name = 'Secondary School');

INSERT INTO institution_templates (tenant_id, name, description, institution_type, configuration_json, is_built_in)
SELECT NULL, 'High School / Sixth Form', 'Ten periods to accommodate option blocks and study periods.', 'HIGH_SCHOOL', '{"bellSchedule": {"name": "High School / Sixth Form Bell Schedule", "periods": [{"name": "Period 1", "startTime": "08:00", "endTime": "08:45", "isBreak": false, "isLunch": false, "ordinal": 1}, {"name": "Period 2", "startTime": "08:45", "endTime": "09:30", "isBreak": false, "isLunch": false, "ordinal": 2}, {"name": "Period 3", "startTime": "09:30", "endTime": "10:15", "isBreak": false, "isLunch": false, "ordinal": 3}, {"name": "Period 4", "startTime": "10:15", "endTime": "11:00", "isBreak": false, "isLunch": false, "ordinal": 4}, {"name": "Lunch", "startTime": "11:00", "endTime": "11:45", "isBreak": false, "isLunch": true, "ordinal": 5}, {"name": "Period 6", "startTime": "11:45", "endTime": "12:30", "isBreak": false, "isLunch": false, "ordinal": 6}, {"name": "Period 7", "startTime": "12:30", "endTime": "13:15", "isBreak": false, "isLunch": false, "ordinal": 7}, {"name": "Period 8", "startTime": "13:15", "endTime": "14:00", "isBreak": false, "isLunch": false, "ordinal": 8}, {"name": "Period 9", "startTime": "14:00", "endTime": "14:45", "isBreak": false, "isLunch": false, "ordinal": 9}, {"name": "Period 10", "startTime": "14:45", "endTime": "15:30", "isBreak": false, "isLunch": false, "ordinal": 10}]}, "settings": {"locale": "en-GB", "timezone": "Europe/London", "schedulingCycle": {"daysInCycle": 5}}, "terminology": {"class": "Class", "period": "Period", "teacher": "Teacher", "subject": "Subject"}, "constraintDefaults": {"lessonLength": 45, "maxConsecutivePeriods": 4}}', TRUE
WHERE NOT EXISTS (SELECT 1 FROM institution_templates WHERE is_built_in = TRUE AND name = 'High School / Sixth Form');

INSERT INTO institution_templates (tenant_id, name, description, institution_type, configuration_json, is_built_in)
SELECT NULL, 'Language School', 'Six periods with longer afternoon blocks for immersion sessions.', 'LANGUAGE', '{"bellSchedule": {"name": "Language School Bell Schedule", "periods": [{"name": "Period 1", "startTime": "08:00", "endTime": "09:00", "isBreak": false, "isLunch": false, "ordinal": 1}, {"name": "Period 2", "startTime": "09:00", "endTime": "10:00", "isBreak": false, "isLunch": false, "ordinal": 2}, {"name": "Period 3", "startTime": "10:00", "endTime": "11:00", "isBreak": false, "isLunch": false, "ordinal": 3}, {"name": "Lunch", "startTime": "11:00", "endTime": "12:00", "isBreak": false, "isLunch": true, "ordinal": 4}, {"name": "Period 5", "startTime": "12:00", "endTime": "13:00", "isBreak": false, "isLunch": false, "ordinal": 5}, {"name": "Period 6", "startTime": "13:00", "endTime": "14:00", "isBreak": false, "isLunch": false, "ordinal": 6}]}, "settings": {"locale": "en-GB", "timezone": "Europe/London", "schedulingCycle": {"daysInCycle": 5}}, "terminology": {"class": "Class", "period": "Period", "teacher": "Teacher", "subject": "Subject"}, "constraintDefaults": {"lessonLength": 60, "maxConsecutivePeriods": 3}}', TRUE
WHERE NOT EXISTS (SELECT 1 FROM institution_templates WHERE is_built_in = TRUE AND name = 'Language School');

INSERT INTO institution_templates (tenant_id, name, description, institution_type, configuration_json, is_built_in)
SELECT NULL, 'Vocational Centre', 'Four long periods to fit extended workshop sessions.', 'VOCATIONAL', '{"bellSchedule": {"name": "Vocational Centre Bell Schedule", "periods": [{"name": "Period 1", "startTime": "08:00", "endTime": "09:30", "isBreak": false, "isLunch": false, "ordinal": 1}, {"name": "Lunch", "startTime": "09:30", "endTime": "11:00", "isBreak": false, "isLunch": true, "ordinal": 2}, {"name": "Period 3", "startTime": "11:00", "endTime": "12:30", "isBreak": false, "isLunch": false, "ordinal": 3}, {"name": "Period 4", "startTime": "12:30", "endTime": "14:00", "isBreak": false, "isLunch": false, "ordinal": 4}]}, "settings": {"locale": "en-GB", "timezone": "Europe/London", "schedulingCycle": {"daysInCycle": 5}}, "terminology": {"class": "Class", "period": "Period", "teacher": "Teacher", "subject": "Subject"}, "constraintDefaults": {"lessonLength": 90, "maxConsecutivePeriods": 2}}', TRUE
WHERE NOT EXISTS (SELECT 1 FROM institution_templates WHERE is_built_in = TRUE AND name = 'Vocational Centre');
